### ISSUE TITLE
useState

### ISSUE THREAD

**Issue by ebdem** [mrtuuro/twitter-clone#5]
`import { useState } from 'react/cjs/react.development';` bunu yapma sebebin neydi neden şu değil  `import React, { useState} from 'react';`

**Comment by mrtuuro** [comment]
hangi dosyada bu

**Comment by ebdem** [comment]
Content.js Dosyası

**Comment by mrtuuro** [comment]
evet evet gördüm, çok saçma olmuş düzelteyim hemen
